In [2]:
import pandas as pd
import numpy as np
import scipy.stats as ss
import matplotlib.pyplot as plt
%matplotlib inline

from keras.models import Sequential, load_model
from keras.layers import Activation, Dense, Dropout, Flatten
from keras import backend
from keras.callbacks import EarlyStopping, ModelCheckpoint
from sklearn.model_selection import train_test_split

Using TensorFlow backend.


In [18]:
#Pandas DataFrame
dataset = pd.read_csv("heston_training.csv")
print (len(dataset))
dataset = dataset.dropna()
print (len(dataset))

210071
189551


In [19]:
X = dataset.iloc[:, :9].values
y = dataset.iloc[:, 9].values

# Use Sklearn library to randomly split data into training/testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(151640, 9) (151640,)
(37911, 9) (37911,)
[[2.00e+00 6.00e-02 2.00e-01 ... 5.00e-01 1.15e+02 9.00e+01]
 [2.00e+00 5.00e-02 5.00e-01 ... 5.00e-01 1.15e+02 1.00e+02]
 [2.00e+00 6.00e-02 1.50e-01 ... 1.00e+00 1.15e+02 8.00e+01]
 ...
 [2.00e+00 6.00e-02 1.50e-01 ... 1.50e+00 1.15e+02 9.00e+01]
 [2.00e+00 6.00e-02 2.00e-01 ... 2.00e+00 1.15e+02 1.10e+02]
 [2.00e+00 5.00e-02 5.50e-01 ... 1.50e+00 1.15e+02 8.00e+01]]
[27.43210053 19.83682757 37.72374229 ... 33.76641558 23.91967607
 40.81595768]


In [20]:
#create model

model = Sequential()
model.add(Dense(40, input_dim=9, kernel_initializer='normal', activation='tanh'))
model.add(Dense(20, kernel_initializer='normal', activation='tanh'))
model.add(Dense(5, kernel_initializer='normal', activation='tanh'))
model.add(Dense(1, kernel_initializer='normal'))

In [21]:
model.compile(loss='mean_absolute_error', optimizer='adam', metrics=['mse', 'mae'])

In [22]:
history = model.fit(X_train, y_train, epochs=10, verbose=1)#, batch_size=10) #epochs = 1000

Epoch 1/10
151640/151640 [==============================] - 21s 140us/step - loss: 13.9014 - mse: 282.4978 - mae: 13.9014
Epoch 2/10
151640/151640 [==============================] - 19s 126us/step - loss: 8.3724 - mse: 98.6599 - mae: 8.3724
Epoch 3/10
151640/151640 [==============================] - 19s 126us/step - loss: 2.9700 - mse: 27.4258 - mae: 2.9700
Epoch 4/10
151640/151640 [==============================] - 19s 128us/step - loss: 0.5167 - mse: 0.5901 - mae: 0.5167
Epoch 5/10
151640/151640 [==============================] - 20s 135us/step - loss: 0.3644 - mse: 0.2428 - mae: 0.3644
Epoch 6/10
151640/151640 [==============================] - 22s 143us/step - loss: 0.3292 - mse: 0.1819 - mae: 0.3292
Epoch 7/10
151640/151640 [==============================] - 22s 143us/step - loss: 0.3039 - mse: 0.1527 - mae: 0.3039
Epoch 8/10
151640/151640 [==============================] - 20s 134us/step - loss: 0.2879 - mse: 0.1388 - mae: 0.2879
Epoch 9/10
151640/151640 [========================

In [23]:
evaluator = model.evaluate(X_train, y_train)
print('Test: {}'.format(evaluator))


151640/151640 [==============================] - 7s 48us/step
Test: [0.43183933368649907, 0.25126439332962036, 0.4318386912345886]


In [24]:
evaluator = model.evaluate(X_test, y_test)
print('Test: {}'.format(evaluator))


37911/37911 [==============================] - 2s 54us/step
Test: [0.4347255048295005, 0.25371837615966797, 0.4347255229949951]


In [ ]:
model.save('heston_model.h5')